from common import *

def write_boundary_files(pd, v, dens=None, dust=True, tracer=None, shear=None):
    '''Write boundary (.bound) files for all fluids.'''
    fnames = []
    n_dust = pd.N
    

    # Get Stokes numbers, dust densities and equilibrium velocities  
    vgx = v[0]
    vgy = v[1]

    # Convert to FARGO standard where y=x and x=y....
    vgx, vgy = vgy, vgx

    if dens is None:
        dens=['exp(-0.5*pow(Zmed(kgh),2))','exp(-0.5*pow(Zmed(kgh),2))','exp(-0.5*pow(Zmed(kgh),2))',\
             'exp(-0.5*pow(Zmed(kact),2))','exp(-0.5*pow(Zmed(kact),2))','exp(-0.5*pow(Zmed(kact),2))']

    if shear is None:
        max_x_act = ' - {}'.format(vgx[1])
        max_x_ghst = ' + {}'.format(vgx[1])
        min_x_act = ' - {}'.format(vgx[0])
        min_x_ghst = ' + {}'.format(vgx[0])
    else:
        max_x_act = ' - {} - QZ*Zmed(kact)'.format(vgx[1])
        max_x_ghst = ' + {} + QZ*Zmed(kgh)'.format(vgx[1])
        min_x_act = ' - {} - QZ*Zmed(kact)'.format(vgx[0])
        min_x_ghst = ' + {} + QZ*Zmed(kgh)'.format(vgx[0])

    #gas ZMAX
    lines = \
        ['//<FLAGS>\n',
        '//#define __GPU\n',
        '//#define __NOPROTO\n',
        '//<\FLAGS>\n',
        '\n',
        '//<INCLUDES>\n',
        '#include "fargo3d.h"\n',
        '#define LEFT  0\n',
        '#define RIGHT 1\n',
        '#define DOWN  2\n',
        '#define UP    3\n',
        '//<\INCLUDES>\n',
        '\n',
        'void boundary_zmax_0_cpu () {\n',
        '\n',
        '//<USER_DEFINED>\n',
        'INPUT(Density);\n',
        'INPUT(Vx);\n',
        'INPUT(Mmx);//MY ADDITION\n',
        'INPUT(Mpx);//MY ADDITION\n',
        'INPUT(Vy);\n',
        'INPUT(Mmy);//MY ADDITION\n',
        'INPUT(Mpy);//MY ADDITION\n',
        'INPUT(Vz);\n',
        'INPUT(Mmz);//MY ADDITION\n',
        'INPUT(Mpz);//MY ADDITION\n',
        'OUTPUT(Density);\n',
        'OUTPUT(Vx);\n',
        'OUTPUT(Vy);\n',
        'OUTPUT(Vz);\n',
        r'//<\USER_DEFINED>',
        '\n',
        '//<INTERNAL>\n',
        'int __attribute__((unused))i;\n',
        'int __attribute__((unused))j;\n',
        'int __attribute__((unused))k;\n',
        'int __attribute__((unused))jact;\n',
        'int __attribute__((unused))jgh;\n',
        'int __attribute__((unused))kact;\n',
        'int __attribute__((unused))kgh;\n',
        'int lgh;\n',
        'int lghs;\n',
        'int lact;\n',
        'int lacts;\n',
        'int lacts_null_mirror;\n',
        'int lacts_null;\n',
        '//<\INTERNAL>\n',
        '\n',
        '//<EXTERNAL>\n',
        'real* density = Density->field_cpu;\n',
        'real* vx = Vx->field_cpu;\n',
        'real* mmx = Mmx->field_cpu;\n',
        'real* mpx = Mpx->field_cpu;\n',
        'real* vy = Vy->field_cpu;\n',
        'real* mmy = Mmy->field_cpu;\n',
        'real* mpy = Mpy->field_cpu;\n',
        'real* vz = Vz->field_cpu;\n',
        'real* mmz = Mmz->field_cpu;\n',
        'real* mpz = Mpz->field_cpu;\n',
        'real dt = StepTime;\n',
        'int size_x = Nx+2*NGHX;\n',
        'int size_y = Ny+2*NGHY;\n',
        'int size_z = NGHZ;\n',
        'int nx = Nx;\n',
        'int ny = Ny;\n',
        'int nz = Nz;\n',
        'int nghy = NGHY;\n',
        'int nghz = NGHZ;\n',
        'int pitch  = Pitch_cpu;\n',
        'int stride = Stride_cpu;\n',
        '//<\EXTERNAL>\n',
        '\n',
        '//<CONSTANT>\n',
        '// real xmin(Nx+2*NGHX+1);\n',
        '// real ymin(Ny+2*NGHY+1);\n',
        '// real zmin(Nz+2*NGHZ+1);\n',
        '//<\CONSTANT>\n',
        '\n',
        '//<MAIN_LOOP>\n',
        '\n',
        'i = j = k = 0;\n',
        'float damping = 1e-3;//damping after factor after 1 omega t\n',
        '\n',
        '#ifdef Z\n',
        'for(k=0; k<size_z; k++) {\n',
        '#endif\n',
        '#ifdef Y\n',
        '    for(j=0; j<size_y; j++) {\n',
        '#endif\n',
        '#ifdef X\n',
        '    for(i=0; i<size_x; i++) {\n',
        '#endif\n',
        '//<#>\n',
        '\n',
        '    lgh = i + j*pitch + (nz+nghz+k)*stride;\n',
        '    lghs = i + j*pitch + (nz+nghz+1+k)*stride;\n',
        '    lact = i + j*pitch + (nz+nghz-1-k)*stride;\n',
        '    lacts = i + j*pitch + (nz+nghz-2-k)*stride;\n',
        '    lacts_null = i + j*pitch + (nz+nghz)*stride;\n',
        '    lacts_null_mirror = i + j*pitch + (nz+nghz-1)*stride;\n',
        '    kgh = (nz+nghz+k);\n',
        '    kact = (nz+nghz-1-k);\n',
        '\n',
        '//CUSTOM BOUNDARIES\n',
        'if (damping < dt){\n',
        '    damping = dt+1e-11;\n',
        '}\n',
        'if (k == 0) {density[lgh] = (density[lact] - '+'{})*(1-dt/damping) + {}'.format(dens[3],dens[2])+';}\n',
        'if (k == 1) {density[lgh] = (density[lact] - '+'{})*(1-dt/damping) + {}'.format(dens[4],dens[1])+';}\n',
        'if (k == 2){density[lgh] = (density[lact] - '+'{})*(1-dt/damping) + {}'.format(dens[5],dens[0])+';}\n',
        'vx[lgh] = ((vx[lact] {} + SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j))*density[lact]/(density[lgh])) * (1-dt/damping) - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j) {};\n'.format(max_x_act,max_x_ghst),  
        'vy[lgh] = (mmy[lact]+mpy[lact-pitch] - ({} * 0.5 * (density[lact]+density[lact-pitch])))/(density[lgh]+density[lgh-pitch]) * (1-dt/damping) + {};\n'.format(vgy[1], vgy[1]),  
        'if (k<size_z-1) {\n',
        '    vz[lgh] = (mmz[lact]+mpz[lacts])/(density[lgh]+density[lgh-stride]) * (1-dt/damping);\n', 
        '}\n',
        'vz[lacts_null] = vz[lacts_null_mirror] * (1-dt/damping);\n',
        '\n',
        '//<\#>\n',
        '#ifdef X\n',
        '    }\n',
        '#endif\n',
        '#ifdef Y\n',
        '    }\n',
        '#endif\n',
        '#ifdef Z\n',
        '}\n',
        '#endif\n',
        '//<\MAIN_LOOP>\n',
        '}\n']


    file_name = 'zmax_bound_'+str(0)+'.c'
    write_file(file_name, lines)
    fnames = fnames + [file_name]

    #ZMIN GAS
    lines = \
        ["//<FLAGS>\n",
        "//#define __GPU\n",
        "//#define __NOPROTO\n",
        "//<\\FLAGS>\n",
        "\n",
        "//<INCLUDES>\n",
        '#include "fargo3d.h"\n',
        "#define LEFT  0\n",
        "#define RIGHT 1\n",
        "#define DOWN  2\n",
        "#define UP    3\n",
        "//<\\INCLUDES>\n",
        "\n",
        "void boundary_zmin_0_cpu () {\n",
        "\n",
        "//<USER_DEFINED>\n",
        'INPUT(Density);\n',
        'INPUT(Vx);\n',
        'INPUT(Mmx);//MY ADDITION\n',
        'INPUT(Mpx);//MY ADDITION\n',
        'INPUT(Vy);\n',
        'INPUT(Mmy);//MY ADDITION\n',
        'INPUT(Mpy);//MY ADDITION\n',
        'INPUT(Vz);\n',
        'INPUT(Mmz);//MY ADDITION\n',
        'INPUT(Mpz);//MY ADDITION\n',
        'OUTPUT(Density);\n',
        "OUTPUT(Vx);\n",
        "OUTPUT(Vy);\n",
        "OUTPUT(Vz);\n",
        "//<\\USER_DEFINED>\n",
        "\n",
        "//<INTERNAL>\n",
        "  int __attribute__((unused))i;\n",
        "  int __attribute__((unused))j;\n",
        "  int __attribute__((unused))k;\n",
        "  int __attribute__((unused))jact;\n",
        "  int __attribute__((unused))jgh;\n",
        "  int __attribute__((unused))kact;\n",
        "  int __attribute__((unused))kgh;\n",
        "  int lgh;\n",
        "  int lghs;\n",
        "  int lact;\n",
        "  int lacts;\n",
        "  int lacts_null_mirror;\n",
        "  int lacts_null;\n",
        "//<\\INTERNAL>\n",
        "\n",
        "//<EXTERNAL>\n",
        "  real* density = Density->field_cpu;\n",
        "  real* vx = Vx->field_cpu;\n",
        '  real* mmx = Mmx->field_cpu;\n',
        '  real* mpx = Mpx->field_cpu;\n',
        "  real* vy = Vy->field_cpu;\n",
        '  real* mmy = Mmy->field_cpu;\n',
        '  real* mpy = Mpy->field_cpu;\n',
        "  real* vz = Vz->field_cpu;\n",
        '  real* mmz = Mmz->field_cpu;\n',
        '  real* mpz = Mpz->field_cpu;\n',
        '  real dt = StepTime;\n',
        "  int size_x = Nx+2*NGHX;\n",
        "  int size_y = Ny+2*NGHY;\n",
        "  int size_z = NGHZ;\n",
        "  int nx = Nx;\n",
        "  int ny = Ny;\n",
        "  int nz = Nz;\n",
        "  int nghy = NGHY;\n",
        "  int nghz = NGHZ;\n",
        "  int pitch  = Pitch_cpu;\n",
        "  int stride = Stride_cpu;\n",
        "//<\\EXTERNAL>\n",
        "\n",
        "//<CONSTANT>\n",
        "// real xmin(Nx+2*NGHX+1);\n",
        "// real ymin(Ny+2*NGHY+1);\n",
        "// real zmin(Nz+2*NGHZ+1);\n",
        "//<\\CONSTANT>\n",
        "\n",
        "//<MAIN_LOOP>\n",
        "\n",
        "  i = j = k = 0;\n",
        'float damping = 1e-3;//damping after factor after 1 omega t\n',
        "\n",
        "#ifdef Z\n",
        "  for(k=0; k<size_z; k++) {\n",
        "#endif\n",
        "#ifdef Y\n",
        "    for(j=0; j<size_y; j++) {\n",
        "#endif\n",
        "#ifdef X\n",
        "      for(i=0; i<size_x; i++) {\n",
        "#endif\n",
        "//<#>\n",
        "\n",
        "  lgh = l;\n",
        "  lghs = l;\n",
        "  lact = i + j*pitch + (2*nghz-k-1)*stride;\n",
        "  lacts = i + j*pitch + (2*nghz-k)*stride;\n",
        "  lacts_null = i + j*pitch + nghz*stride;\n",
        "  lacts_null_mirror = i + j*pitch + (nghz+1)*stride;\n",
        "  kgh = k;\n",
        "  kact = (2*nghz-k-1);\n",
        '\n',
        '//CUSTOM BOUNDARIES\n',
        'if (damping < dt){\n',
        '    damping = dt+1e-11;\n',
        '}\n',
        'if (k == 0) {density[lgh] = (density[lact] - '+'{})*(1-dt/damping) + {}'.format(dens[5],dens[0])+';}\n',
        'if (k == 1) {density[lgh] = (density[lact] - '+'{})*(1-dt/damping) + {}'.format(dens[4],dens[1])+';}\n',
        'if (k == 2){density[lgh] = (density[lact] - '+'{})*(1-dt/damping) + {}'.format(dens[3],dens[2])+';}\n',
        'vx[lgh] = ((vx[lact] {} + SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j))*density[lact]/(density[lgh])) * (1-dt/damping) - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j) {};\n'.format(min_x_act,min_x_ghst),  
        'vy[lgh] = (mmy[lact]+mpy[lact-pitch] - ({} * 0.5 * (density[lact]+density[lact-pitch])))/(density[lgh]+density[lgh-pitch]) * (1-dt/damping) + {};\n'.format(vgy[0], vgy[0]),  
        'if (k<size_z-1) {\n',
        '    vz[lgh] = (mmz[lact]+mpz[lacts])/(density[lgh]+density[lgh-stride]) * (1-dt/damping);\n', 
        '}\n',
        'vz[lacts_null] = vz[lacts_null_mirror] * (1-dt/damping);\n',
        '\n',
        "//<\\#>\n",
        "#ifdef X\n",
        "      }\n",
        "#endif\n",
        "#ifdef Y\n",
        "    }\n",
        "#endif\n",
        "#ifdef Z\n",
        "  }\n",
        "#endif\n",
        "//<\\MAIN_LOOP>\n",
        "}\n"]


    file_name = 'zmin_bound_'+str(0)+'.c'
    write_file(file_name, lines)
    fnames = fnames + [file_name]

    #dust
    if dust:
        for i in range(1, n_dust+1):
            #ZMax
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_zmax_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vx);\n",
                "INPUT(Vy);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vx);\n",
                "OUTPUT(Vy);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vx = Vx->field_cpu;\n",
                "  real* vy = Vy->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = Ny+2*NGHY;\n",
                "  int size_z = NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "    lgh = i + j*pitch + (nz+nghz+k)*stride;\n",
                "    lghs = i + j*pitch + (nz+nghz+1+k)*stride;\n",
                "    lact = i + j*pitch + (nz+nghz-1-k)*stride;\n",
                "    lacts = i + j*pitch + (nz+nghz-1-k)*stride;\n",
                "    lacts_null = i + j*pitch + (nz+nghz)*stride;\n",
                "    lacts_null_mirror = i + j*pitch + (nz+nghz-1)*stride;\n",
                "    kgh = (nz+nghz+k);\n",
                "    kact = (nz+nghz-1-k);\n",
                "\n",
                "  //CUSTOM BOUNDARIES\n",
                "    density[lgh] = density[lact];\n",
                "    vx[lgh] = vx[lact];\n",
                "    vy[lgh] = vy[lact];\n",
                "    if (k<size_z-1){\n",
                "      if (vz[lact]>0){\n",
                "        vz[lghs] = vz[lact];\n",
                "        vz[lacts_null] = vz[lacts_null_mirror];\n",
                "      }\n",
                "      else {\n",
                "        vz[lghs] = 0;\n",
                "        vz[lacts_null] = 0;\n",
                "      }\n",
                "    }\n",
                "\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]


            file_name = 'zmax_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]


            
            #ZMIN
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_zmin_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vx);\n",
                "INPUT(Vy);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vx);\n",
                "OUTPUT(Vy);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vx = Vx->field_cpu;\n",
                "  real* vy = Vy->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = Ny+2*NGHY;\n",
                "  int size_z = NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "	lgh = l;\n",
                "	lghs = l;\n",
                "	lact = i + j*pitch + (2*nghz-k-1)*stride;\n",
                "	lacts = i + j*pitch + (2*nghz-k)*stride;\n",
                "	lacts_null = i + j*pitch + nghz*stride;\n",
                "	lacts_null_mirror = i + j*pitch + (nghz+1)*stride;\n",
                "	kgh = k;\n",
                "	kact = (2*nghz-k-1);\n",
                "\n",
                "\n",
                "  //CUSTOM BOUNDARIES\n",
                "    density[lgh] = density[lact];\n",
                "    vx[lgh] = vx[lact];\n",
                "    vy[lgh] = vy[lact];\n",
                "    if (k<size_z-1){\n",
                "      if (vz[lact]<0){\n",
                "        vz[lghs] = vz[lact];\n",
                "        vz[lacts_null] = vz[lacts_null_mirror];\n",
                "      }\n",
                "      else {\n",
                "        vz[lghs] = 0;\n",
                "        vz[lacts_null] = 0;\n",
                "      }\n",
                "    }\n",
                "\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]
                

            file_name = 'zmin_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]

            #YMIN    
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_ymin_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = NGHY;\n",
                "  int size_z = Nz+2*NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "    lgh = l;\n",
                "    lghs = l;\n",
                "    lact = i + (2*nghy-j-1)*pitch + k*stride;\n",
                "    lacts = i + (2*nghy-j)*pitch + k*stride;\n",
                "    lacts_null = i + nghy*pitch + k*stride;\n",
                "    lacts_null_mirror = i + (nghy+1)*pitch + k*stride;\n",
                "    jgh = j;\n",
                "    jact = (2*nghy-j-1);\n",
                "\n",
                "    density[lgh] = density[lact];\n",
                "    vz[lgh] = vz[lact]*density[lact]/density[lgh];\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]

            file_name = 'ymin_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]

            #YMax
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_ymax_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = NGHY;\n",
                "  int size_z = Nz+2*NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "  lgh = i + (ny+nghy+j)*pitch + k*stride;\n",
                "  lghs = i + (ny+nghy+1+j)*pitch + k*stride;\n",
                "  lact = i + (ny+nghy-1-j)*pitch + k*stride;\n",
                "  lacts = i + (ny+nghy-1-j)*pitch + k*stride;\n",
                "  lacts_null = i + (ny+nghy)*pitch + k*stride;\n",
                "  lacts_null_mirror = i + (ny+nghy-1)*pitch + k*stride;\n",
                "  jgh = (ny+nghy+j);\n",
                "  jact = (ny+nghy-1-j);\n",
                "\n",
                "  density[lgh] = density[lact];\n",
                "  vz[lgh] = vz[lact]*density[lact]/density[lgh];\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]


            file_name = 'ymax_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]

    if tracer is not None:
        n_tracer = len(tracer)
        #ZMax
        if dust:
                j = pd.N+1
        else:
                j = 1
        for i in range(j, n_tracer+j):
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_zmax_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vx);\n",
                "INPUT(Vy);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vx);\n",
                "OUTPUT(Vy);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vx = Vx->field_cpu;\n",
                "  real* vy = Vy->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = Ny+2*NGHY;\n",
                "  int size_z = NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "    lgh = i + j*pitch + (nz+nghz+k)*stride;\n",
                "    lghs = i + j*pitch + (nz+nghz+1+k)*stride;\n",
                "    lact = i + j*pitch + (nz+nghz-1-k)*stride;\n",
                "    lacts = i + j*pitch + (nz+nghz-1-k)*stride;\n",
                "    lacts_null = i + j*pitch + (nz+nghz)*stride;\n",
                "    lacts_null_mirror = i + j*pitch + (nz+nghz-1)*stride;\n",
                "    kgh = (nz+nghz+k);\n",
                "    kact = (nz+nghz-1-k);\n",
                "\n",
                "  //CUSTOM BOUNDARIES\n",
                "    density[lgh] = density[lact];\n",
                "    vx[lgh] = vx[lact];\n",
                "    vy[lgh] = vy[lact];\n",
                "    if (k<size_z-1){\n",
                "      if (vz[lact]>0){\n",
                "        vz[lghs] = vz[lact];\n",
                "        vz[lacts_null] = vz[lacts_null_mirror];\n",
                "      }\n",
                "      else {\n",
                "        vz[lghs] = 0;\n",
                "        vz[lacts_null] = 0;\n",
                "      }\n",
                "    }\n",
                "\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]


            file_name = 'zmax_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]


            #ZMIN
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_zmin_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vx);\n",
                "INPUT(Vy);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vx);\n",
                "OUTPUT(Vy);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vx = Vx->field_cpu;\n",
                "  real* vy = Vy->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = Ny+2*NGHY;\n",
                "  int size_z = NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "	lgh = l;\n",
                "	lghs = l;\n",
                "	lact = i + j*pitch + (2*nghz-k-1)*stride;\n",
                "	lacts = i + j*pitch + (2*nghz-k)*stride;\n",
                "	lacts_null = i + j*pitch + nghz*stride;\n",
                "	lacts_null_mirror = i + j*pitch + (nghz+1)*stride;\n",
                "	kgh = k;\n",
                "	kact = (2*nghz-k-1);\n",
                "\n",
                "\n",
                "  //CUSTOM BOUNDARIES\n",
                "    density[lgh] = density[lact];\n",
                "    vx[lgh] = vx[lact];\n",
                "    vy[lgh] = vy[lact];\n",
                "    if (k<size_z-1){\n",
                "      if (vz[lact]<0){\n",
                "        vz[lghs] = vz[lact];\n",
                "        vz[lacts_null] = vz[lacts_null_mirror];\n",
                "      }\n",
                "      else {\n",
                "        vz[lghs] = 0;\n",
                "        vz[lacts_null] = 0;\n",
                "      }\n",
                "    }\n",
                "\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]
                

            file_name = 'zmin_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]

            #YMIN    
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_ymin_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = NGHY;\n",
                "  int size_z = Nz+2*NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "    lgh = l;\n",
                "    lghs = l;\n",
                "    lact = i + (2*nghy-j-1)*pitch + k*stride;\n",
                "    lacts = i + (2*nghy-j)*pitch + k*stride;\n",
                "    lacts_null = i + nghy*pitch + k*stride;\n",
                "    lacts_null_mirror = i + (nghy+1)*pitch + k*stride;\n",
                "    jgh = j;\n",
                "    jact = (2*nghy-j-1);\n",
                "\n",
                "    density[lgh] = density[lact];\n",
                "    vz[lgh] = vz[lact]*density[lact]/density[lgh];\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]

            file_name = 'ymin_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]

            #YMax
            lines = \
                ["//<FLAGS>\n",
                "//#define __GPU\n",
                "//#define __NOPROTO\n",
                "//<\\FLAGS>\n",
                "\n",
                "//<INCLUDES>\n",
                '#include "fargo3d.h"\n',
                "#define LEFT  0\n",
                "#define RIGHT 1\n",
                "#define DOWN  2\n",
                "#define UP    3\n",
                "//<\\INCLUDES>\n",
                "\n",
                "void boundary_ymax_"+str(i)+"_cpu () {\n",
                "\n",
                "//<USER_DEFINED>\n",
                "INPUT(Density);\n",
                "INPUT(Vz);\n",
                "OUTPUT(Density);\n",
                "OUTPUT(Vz);\n",
                "//<\\USER_DEFINED>\n",
                "\n",
                "//<INTERNAL>\n",
                "  int __attribute__((unused))i;\n",
                "  int __attribute__((unused))j;\n",
                "  int __attribute__((unused))k;\n",
                "  int __attribute__((unused))jact;\n",
                "  int __attribute__((unused))jgh;\n",
                "  int __attribute__((unused))kact;\n",
                "  int __attribute__((unused))kgh;\n",
                "  int lgh;\n",
                "  int lghs;\n",
                "  int lact;\n",
                "  int lacts;\n",
                "  int lacts_null_mirror;\n",
                "  int lacts_null;\n",
                "//<\\INTERNAL>\n",
                "\n",
                "//<EXTERNAL>\n",
                "  real* density = Density->field_cpu;\n",
                "  real* vz = Vz->field_cpu;\n",
                "  int size_x = Nx+2*NGHX;\n",
                "  int size_y = NGHY;\n",
                "  int size_z = Nz+2*NGHZ;\n",
                "  int nx = Nx;\n",
                "  int ny = Ny;\n",
                "  int nz = Nz;\n",
                "  int nghy = NGHY;\n",
                "  int nghz = NGHZ;\n",
                "  int pitch  = Pitch_cpu;\n",
                "  int stride = Stride_cpu;\n",
                "//<\\EXTERNAL>\n",
                "\n",
                "//<CONSTANT>\n",
                "// real xmin(Nx+2*NGHX+1);\n",
                "// real ymin(Ny+2*NGHY+1);\n",
                "// real zmin(Nz+2*NGHZ+1);\n",
                "//<\\CONSTANT>\n",
                "\n",
                "//<MAIN_LOOP>\n",
                "\n",
                "  i = j = k = 0;\n",
                "\n",
                "#ifdef Z\n",
                "  for(k=0; k<size_z; k++) {\n",
                "#endif\n",
                "#ifdef Y\n",
                "    for(j=0; j<size_y; j++) {\n",
                "#endif\n",
                "#ifdef X\n",
                "      for(i=0; i<size_x; i++) {\n",
                "#endif\n",
                "//<#>\n",
                "\n",
                "  lgh = i + (ny+nghy+j)*pitch + k*stride;\n",
                "  lghs = i + (ny+nghy+1+j)*pitch + k*stride;\n",
                "  lact = i + (ny+nghy-1-j)*pitch + k*stride;\n",
                "  lacts = i + (ny+nghy-1-j)*pitch + k*stride;\n",
                "  lacts_null = i + (ny+nghy)*pitch + k*stride;\n",
                "  lacts_null_mirror = i + (ny+nghy-1)*pitch + k*stride;\n",
                "  jgh = (ny+nghy+j);\n",
                "  jact = (ny+nghy-1-j);\n",
                "\n",
                "  density[lgh] = density[lact];\n",
                "  vz[lgh] = vz[lact]*density[lact]/density[lgh];\n",
                "//<\\#>\n",
                "#ifdef X\n",
                "      }\n",
                "#endif\n",
                "#ifdef Y\n",
                "    }\n",
                "#endif\n",
                "#ifdef Z\n",
                "  }\n",
                "#endif\n",
                "//<\\MAIN_LOOP>\n",
                "}\n"]


            file_name = 'ymax_bound_'+str(i)+'.c'
            write_file(file_name, lines)
            fnames = fnames + [file_name]



    return fnames
