import numpy as np
import random
from common import *

def rand_abs_between(a: float, b: float) -> float:
    if not (a >= 0 and b > 0 and a < b):
        raise ValueError("Require 0 ≤ a < b.")
    mag = random.uniform(a, b)      # magnitude in (a, b); endpoints have prob 0
    return mag if random.random() < 0.5 else -mag

def write_condinit_file(pd, Nz, equilibrium, perturbation=None, acceleration_gas=False, dust=True, tracer=None, shear=None, const_dust_size=False):
  '''Write FARGO condinit.c file
  Args:
      pd: PolyDust object initial conditions independt of z.
      Nz: int, number of gridpoint in the vertical direction
      equilibrium (optional): str, pathname to csv file of z dependent initial condition in equlibiruim or None if no specif z dependicy
      perturbation (optional): List of strings governing velocity perturbations, or None in case of no perturbations. Usually generated by Perturbation.to_string().
      acceleration_gas (optional): Adds the value of background acceleration
  '''

  #add string for initial shear velocity to gas
  if shear is None:
    shear_str = ''
  else:
    shear_str = ' + QZ*Zmin(k)'

  #add string for white noise or single mode pertibation
  if perturbation is None:
    amp = 0.0
    pert = ''
  elif type(perturbation) == list and len(perturbation) == 4:
    amp = perturbation[0]
    pert = ''
  elif type(perturbation) == float:
    amp = perturbation
    pert = '+ AMP *(randm()-0.5)*2.0'
  else:
    amp = perturbation[0]
    eign = 1.
    pert = '+ AMP*{}*cos({}*Ymed(j) + {}*Zmed(k))'.format(eign, perturbation[1], perturbation[2])

  # background velocities with fixed dust/gas ratio
  stokes, sigma, v = pd.initial_conditions()
  vgx = v[0]
  vgy = v[1]
  vgz = v[2]

  vdx = v[3::3]
  vdy = v[4::3]
  vdz = v[5::3]
  # Convert to FARGO standard where y=x and x=y....
  vgx, vgy = vgy, vgx
  vdx, vdy = vdy, vdx

  lines = \
    ['#include "fargo3d.h"\n\n',
    '#include <stdlib.h>\n',
    '#include <stdio.h>\n',
    '#include <string.h>\n\n',
    '#define MAX_ROWS {}\n'.format(Nz+7)]
  
  # add code to read in equilibrium initial condition table
  if equilibrium is not None:
    lines.extend(['#define MAX_ROWS {}\n'.format(Nz+7),
                  '#define MAX_COLS {}\n'.format(pd.N*4+7),
                  '#define MAX_LINE_LENGTH 1024\n\n'])

  #setup intial condition code
  lines.extend(\
    ['float randm() {return ((float)rand()/RAND_MAX);}\n\n',
    '/* ---- float: |x| in (a, b) ---- */\n',
    'float randabs(float a, float b) {\n',
    '    float mag = a + randm() * (b - a);\n',
    '    int sign = (rand() & 1) ? 1 : -1;\n\n',
    '    return sign * mag;\n',
    '}\n\n',
    'void CondInit() {\n',
    '  int id_gas = 0;\n',
    '  int feedback = YES;\n'])
  
  if equilibrium is not None:
    lines.extend(\
      ['  //We read in the .csv file with initial conditions\n',
      '  double matrix[MAX_ROWS][MAX_COLS];\n',
      '  char line[MAX_LINE_LENGTH];\n',
      '  int row = 0;\n',
      '\n',
      '  FILE *file = fopen("{}/initial.csv", "r");\n'.format(equilibrium),
      '  if (!file) {\n',
      '      perror("Failed to open file");\n',
      '  }\n',
      '\n',
      '  while (fgets(line, sizeof(line), file) && row < MAX_ROWS) {\n',
      '    int col = 0;\n',
      '    char *token = strtok(line, ",");\n', 
      '    while (token && col < MAX_COLS) {\n', 
      '      matrix[row][col] = atof(token);\n', 
      '      token = strtok(NULL, ",");\n', 
      '      col++;\n', 
      '    }\n',
      '    row++;\n',
      '  }\n',
      '\n\n'])
  
  # code initial conditions
  lines.extend(\
    ['  //We first create the gaseous fluid and store it in the array Fluids\n',
    '  Fluids[id_gas] = CreateFluid("gas",GAS);\n\n',
    '  //We now select the fluid\n',
    '  SelectFluid(id_gas);\n',
    '  //and fill its fields\n',
    '  int i,j,k;\n',
    '  float AMP;\n',
    '  real *rho  = Density->field_cpu;\n',
    '  real *cs   = Energy->field_cpu;\n',
    '  real *vx   = Vx->field_cpu;\n',
    '  real *vy   = Vy->field_cpu;\n',
    '  real *vz   = Vz->field_cpu;\n'])
  
  if acceleration_gas and equilibrium is not None:
    lines.extend(\
      ['#ifdef ACCELERATIONGAS\n'
        '  real *agasx = Agasx->field_cpu;\n',
        '  real *agasy = Agasy->field_cpu;\n',
        '  real *agasz = Agasz->field_cpu;\n',
        '#endif\n'])
    
  lines.extend(\
    ['  k = NGHZ;\n',
    '  AMP = {};\n'.format(amp),
    '  srand(CPU_Rank);\n'
    '  for (k=0; k<Nz+2*NGHZ; k++) {\n',
    '    for (j=0; j<Ny+2*NGHY; j++) {\n',
    '      for (i=0; i<Nx+2*NGHX; i++) {\n',
    '        cs[l]  = 1.0;\n'])
  
  # read from matrix of stored intitial condition table
  if equilibrium is not None:
    lines.extend(\
      ['        rho[l] = matrix[k+z0cell+1][0];\n',
      '        vx[l]  = matrix[k+z0cell+1][2]'+pert+' - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j)'+shear_str+';\n',
      '        vy[l]  = matrix[k+z0cell+1][1]'+pert+';\n',
      '        vz[l]  = matrix[k+z0cell+1][3]'+pert+';\n'])
    if acceleration_gas:
      lines.extend(\
        ['#ifdef ACCELERATIONGAS\n',
        '        agasx[l]  = matrix[k+z0cell+1][5];\n',
        '        agasy[l]  = matrix[k+z0cell+1][4];\n',
        '        agasz[l]  = matrix[k+z0cell+1][6];\n',
        '#endif\n'])
  else:
    lines.extend(\
      ['        rho[l] = 1.0*exp(-0.5*(pow(Zmed(k),2)));\n',
      '        vx[l]  = {} '.format(vgx)+pert+' - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j)'+shear_str+';\n',
      '        vy[l]  = {} '.format(vgy)+pert+';\n',
      '        vz[l]  = {} '.format(vgz)+pert+';\n'])
  if type(perturbation) == list and len(perturbation) == 4:
    lines.extend(\
      ['        srand(123456u);\n',
      '        int m;\n',
      '        for (m=0; m<'+str(perturbation[3])+'; m++) {\n',
      '          float yrand = randabs({},{}) ;\n'.format(perturbation[1][0], perturbation[1][1]),
      '          float zrand = randabs({},{}) ;\n'.format(perturbation[2][0], perturbation[2][1]),
      '          vx[l] += AMP*{}*cosf(2*M_PI*randm() + yrand*Ymed(j) + zrand*Zmed(k));\n'.format(1./perturbation[3]),
      '          vy[l] += AMP*{}*cosf(2*M_PI*randm() + yrand*Ymed(j) + zrand*Zmed(k));\n'.format(1./perturbation[3]),
      '          vz[l] += AMP*{}*cosf(2*M_PI*randm() + yrand*Ymed(j) + zrand*Zmed(k));\n'.format(1./perturbation[3]),
      '        }\n']) 
  lines.extend(\
    ['      }\n',
    '    }\n',
    '  }\n'])

  #add code for dust
  if dust is True:
    lines.extend(\
      ['  \n  //We repeat the process for the dust fluids\n',
      '  char dust_name[MAXNAMELENGTH];\n'])
    for n in range(0, pd.N):
      lines.extend(\
        ['  sprintf(dust_name,"dust%d",{}); //We assign different names to the dust fluids\n'.format(n+1),
        '  Fluids[{}]  = CreateFluid(dust_name, DUST);\n'.format(n+1),
        '  SelectFluid({});\n'.format(n+1),
        '  float invsize{};\n'.format(n+1),
        '  rho  = Density->field_cpu;\n',
        '  cs   = Energy->field_cpu;\n',
        '  vx   = Vx->field_cpu;\n',
        '  vy   = Vy->field_cpu;\n',
        '  vz   = Vz->field_cpu;\n'
        '  for (k=0; k<Nz+2*NGHZ; k++) {\n',
        '    for (j=0; j<Ny+2*NGHY; j++) {\n',
        '      for (i=0; i<Nx+2*NGHX; i++) {\n'])
      
      # read from matrix of stored intitial condition table
      if equilibrium is not None:
        lines.extend(\
          ['        rho[l] = matrix[k+z0cell+1][{}];\n'.format(int((1+n)*4+3)),
          '        vx[l]  = matrix[k+z0cell+1][{}]'.format(int(2+((1+n)*4)+3)) + ' - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j)'+shear_str+';\n',
          '        vy[l]  = matrix[k+z0cell+1][{}]'.format(int(1+((1+n)*4))+3) + ';\n',
          '        vz[l]  = matrix[k+z0cell+1][{}]'.format(int(3+((1+n)*4))+3)+ ';\n'])
      # 
      else:
        lines.extend(\
          ['        rho[l] = {}*exp(-0.5*(pow(Zmed(k),2)));\n'.format(sigma[n]),
          '        vx[l]  = {} '.format(vdx[n]) + ' - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j)'+shear_str+';\n',
          '        vy[l]  = {} '.format(vdy[n]) +  ';\n'])
      # take into account settling velocity for constant size vs constant Stokes  
      if const_dust_size:
        lines.extend(['        vz[l]  = {} '.format(vdz[n]) + ' - OMEGAFRAME * OMEGAFRAME * Zmin(k) / (INVSTOKES'+str(n+1)+'*exp(-0.5*(pow(Zmin(k),2))));\n'])
      else:
        lines.extend(['        vz[l]  = {} '.format(vdz[n]) + ' - OMEGAFRAME * OMEGAFRAME * Zmin(k) / INVSTOKES'+str(n+1)+';\n'])
      
      lines.extend(\
        ['        cs[l]  = 0.0;\n',
        '      }\n',
        '    }\n',
        '  }\n\n'])

    # add code for dust feedback in constant size and constant Stokes setup
    lines.extend(\
        ['  /*We now fill the collision matrix (Feedback from dust included)\n',
        '  Note: ColRate() moves the collision matrix to the device.\n',
        '  If feedback=NO, gas does not feel the drag force.*/\n'])
    for n in range(0, pd.N):
      if const_dust_size:
        lines.extend(\
        ['  invsize{}'.format(n+1)+' = sqrt(M_PI/8)*INVSTOKES{}'.format(n+1)+'*BULKDENSITY;\n',
         '  ColRate(invsize'+str(n+1)+', id_gas, '+str(n+1)+', feedback);\n']) 
      else:
        lines.extend(['  ColRate(INVSTOKES'+str(n+1)+', id_gas, '+str(n+1)+', feedback);\n'])
      
  # add tracer particle if relevant
  if tracer is not None:
    n_tracer = len(tracer)
    lines.extend(\
      ['  \n  //We repeat the process for the dust fluids\n',
      '  char tracer_name[MAXNAMELENGTH];\n'])
    for i in range(n_tracer):
      lines.extend(\
        ['  sprintf(tracer_name,"tracer%d",{}); //We assign different names to the dust fluids\n'.format(i+1)])
      if dust is True:
        lines.extend(\
          ['  Fluids[{}]  = CreateFluid(tracer_name, TRACER);\n'.format(pd.N+1+i),
          '  SelectFluid({});\n'.format(pd.N+1+i)])
      else:
        lines.extend(\
          ['  Fluids[{}]  = CreateFluid(tracer_name, TRACER);\n'.format(1+i),
          '  SelectFluid({});\n'.format(1+i)])        

      lines.extend(\
        ['  rho  = Density->field_cpu;\n',
        '  cs   = Energy->field_cpu;\n',
        '  vx   = Vx->field_cpu;\n',
        '  vy   = Vy->field_cpu;\n',
        '  vz   = Vz->field_cpu;\n',
        '  for (k=0; k<Nz+2*NGHZ; k++) {\n',
        '    for (j=0; j<Ny+2*NGHY; j++) {\n',
        '      for (i=0; i<Nx+2*NGHX; i++) {\n',
        '        rho[l] = FTRACER{}*erf(ZMAX/sqrt(2))/(HTRACER{}*erf(ZMAX/(sqrt(2)*HTRACER{})))*exp(-0.5*pow(Zmed(k)/HTRACER{},2));\n'.format(i,i,i,i),
        '        vx[l]  = 0.0 - SHEARPARAM*OMEGAFRAME*OMEGAFRAME*Ymed(j)'+shear_str+';\n',
        '        vy[l]  = 0.0;\n',
        '        vz[l]  = 0.0;\n',
        '        cs[l]  = 0.0;\n',
        '      }\n',
        '    }\n',
        '  }\n\n'])
      if dust is True:
        lines.extend(\
          ['  /*feedback=NO, gas does not feel the drag force.*/\n',
          '  ColRate(INVSTOKESTRACER{}, id_gas, {}, NO);\n'.format(i,pd.N+1+i)])
      else:
        lines.extend(\
          ['  /*feedback=NO, gas does not feel the drag force.*/\n',
          '  ColRate(INVSTOKESTRACER{}, id_gas, {}, NO);\n'.format(i, i+1)])
  add_line(lines, '}\n')

  fname = 'condinit.c'
  write_file(fname, lines)
  0,

  return fname
